client
dev tun
proto udp4

remote 192.168.62.253 1194

resolv-retry infinite
nobind

persist-key
persist-tun

ca /etc/openvpn/client/ca.crt
cert /etc/openvpn/client/remote-employee.crt
key /etc/openvpn/client/remote-employee.key

tls-crypt /etc/openvpn/client/ta.key
tls-version-min 1.2

remote-cert-tls server
verify-x509-name companyrouter name

data-ciphers AES-256-GCM:AES-128-GCM
auth SHA256

verb 3