port 1194
proto udp4
dev tun

topology subnet
server 10.9.0.0 255.255.255.0

push "route 172.30.0.0 255.255.0.0"

ca /etc/openvpn/server/ca.crt
cert /etc/openvpn/server/companyrouter.crt
key /etc/openvpn/server/companyrouter.key
dh /etc/openvpn/server/dh.pem
crl-verify /etc/openvpn/server/crl.pem

tls-crypt /etc/openvpn/server/ta.key
tls-version-min 1.2

verify-client-cert require
remote-cert-tls client

data-ciphers AES-256-GCM:AES-128-GCM
auth SHA256

keepalive 10 60
persist-key
persist-tun

verb 3
